# ─────────────────────────────────────────────────────────────────────────────
# SSM Parameter Store — AES-256-GCM key for Google OAuth refresh tokens
#
# Replaces the former customer-managed KMS key (removed to cut cost). A single
# 32-byte symmetric key is generated by Terraform, base64-encoded, and stored
# as a SecureString parameter. Lambdas fetch it once at cold start
# (WithDecryption=True) and encrypt/decrypt tokens in-process with AES-GCM.
#
# Used by:
#   * OAuth Callback Lambda  → reads key to encrypt the stored refresh token
#   * Google Docs Writer     → reads key to decrypt before refreshing access
#
# Per-user binding: chat_id is passed as AES-GCM AAD (additional authenticated
# data) instead of a KMS EncryptionContext — same security property, decryption
# fails if the chat_id doesn't match the one used at encrypt time.
#
# NOTE: existing KMS-encrypted tokens in DynamoDB are unreadable after this
# migration — affected users must re-authenticate via OAuth (/oauth/start).
# ─────────────────────────────────────────────────────────────────────────────

# 32 random bytes (AES-256). `.base64` is what we persist; Lambda base64-decodes
# it back to raw key bytes at runtime.
resource "random_bytes" "token_encryption_key" {
  length = 32
}

resource "aws_ssm_parameter" "token_encryption_key" {
  name        = "/${var.project_name}/${var.environment}/token-encryption-key"
  description = "AES-256-GCM key for encrypting Google OAuth refresh tokens"
  type        = "SecureString"
  value       = random_bytes.token_encryption_key.base64

  tags = {
    Name = "${var.project_name}-${var.environment}-token-encryption-key"
  }

  lifecycle {
    # Never overwrite a rotated key. Operators can rotate by updating the
    # parameter value out-of-band; Terraform must not clobber it on apply.
    ignore_changes = [value]
  }
}
