"""
Token encryption helper — AES-256-GCM for Google OAuth refresh tokens.

This module replaces the previous AWS KMS implementation (removed to cut cost).
Instead of round-tripping to KMS on every encrypt/decrypt, we hold a single
32-byte symmetric key and do AES-256-GCM in-process.

Key management:
  * The key is generated by Terraform and stored base64-encoded in SSM
    Parameter Store as a SecureString (path ``/{project}/{env}/token-encryption-key``).
  * It is fetched once at Lambda cold start with ``WithDecryption=True`` and
    cached at module level, so warm invocations skip the SSM round trip.

Per-user binding:
  ``chat_id`` is passed as the AES-GCM AAD (additional authenticated data),
  replicating the old KMS EncryptionContext ``{"chat_id": "<id>"}``. The AAD is
  authenticated but not encrypted: decryption fails with an InvalidTag error if
  the supplied chat_id doesn't match the one used at encrypt time, so a leaked
  DynamoDB row cannot be replayed against a different user.

Storage format:
  ``base64(nonce || ciphertext)`` where ``nonce`` is a random 96-bit value and
  ``ciphertext`` already includes the GCM authentication tag. Safe to store as a
  DynamoDB ``S`` attribute.

MIGRATION NOTE: tokens encrypted by the old KMS implementation are UNREADABLE
after this change (different algorithm + key). Affected users must
re-authenticate via OAuth (/oauth/start) to store a fresh AES-GCM ciphertext.
"""

from __future__ import annotations

import base64
import logging
import os

import boto3
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

logger = logging.getLogger(__name__)

# 96-bit nonce — the size recommended for AES-GCM. Stored as a prefix on the
# ciphertext so decrypt can recover it.
NONCE_SIZE = 12

# AWS clients are cheap to create and safe to reuse across warm invocations.
_region = os.environ.get("AWS_REGION", "ap-south-1")
_ssm = boto3.client("ssm", region_name=_region)

# Cold-start cache of the decrypted 32-byte key.
_key_cache: bytes | None = None


class TokenEncryptionError(RuntimeError):
    """Raised when encryption/decryption fails (missing key, tampered ciphertext, chat_id mismatch)."""


def _load_key() -> bytes:
    """Fetch + cache the 32-byte AES key from SSM Parameter Store.

    The parameter holds the key base64-encoded as a SecureString; we fetch it
    with ``WithDecryption=True`` and decode to raw bytes. Cached at module level
    so only the first (cold-start) call pays the SSM round trip.
    """
    global _key_cache
    if _key_cache is not None:
        return _key_cache

    param_name = os.environ["TOKEN_KEY_PARAM"]
    try:
        resp = _ssm.get_parameter(Name=param_name, WithDecryption=True)
    except Exception as exc:  # boto3 ClientError or network
        logger.error("Failed to fetch token key from SSM '%s': %s", param_name, exc)
        raise TokenEncryptionError(f"Could not load token encryption key: {exc}") from exc

    try:
        key = base64.b64decode(resp["Parameter"]["Value"])
    except (KeyError, ValueError, TypeError) as exc:
        raise TokenEncryptionError(f"Token key in SSM is not valid base64: {exc}") from exc

    if len(key) != 32:
        raise TokenEncryptionError(
            f"Token key must be 32 bytes (AES-256); got {len(key)} bytes"
        )

    _key_cache = key
    return key


def encrypt_refresh_token(*, chat_id: str, refresh_token: str) -> str:
    """Encrypt ``refresh_token`` with AES-256-GCM and return base64(nonce||ciphertext).

    ``chat_id`` is bound to the ciphertext as AAD — the same value must be
    supplied at decrypt time. The returned string is safe to store as a
    DynamoDB ``S`` attribute.
    """
    if not refresh_token:
        raise ValueError("refresh_token must be non-empty")
    if not chat_id:
        raise ValueError("chat_id must be non-empty (used as AES-GCM AAD)")

    key = _load_key()
    nonce = os.urandom(NONCE_SIZE)
    try:
        ciphertext = AESGCM(key).encrypt(
            nonce,
            refresh_token.encode("utf-8"),
            str(chat_id).encode("utf-8"),
        )
    except Exception as exc:
        logger.error("AES-GCM encrypt failed for chat_id=%s: %s", chat_id, exc)
        raise TokenEncryptionError(f"Token encryption failed: {exc}") from exc

    return base64.b64encode(nonce + ciphertext).decode("ascii")


def decrypt_refresh_token(*, chat_id: str, ciphertext_b64: str) -> str:
    """Reverse of :func:`encrypt_refresh_token`.

    The same ``chat_id`` used at encrypt time must be supplied as AAD or the GCM
    tag check fails (raised as :class:`TokenEncryptionError`). This also covers
    any tampering with the stored ciphertext.
    """
    if not ciphertext_b64:
        raise ValueError("ciphertext is empty")

    try:
        blob = base64.b64decode(ciphertext_b64)
    except (ValueError, TypeError) as exc:
        raise TokenEncryptionError(f"Stored ciphertext is not valid base64: {exc}") from exc

    if len(blob) <= NONCE_SIZE:
        raise TokenEncryptionError("Stored ciphertext is too short to contain a nonce")

    nonce, ciphertext = blob[:NONCE_SIZE], blob[NONCE_SIZE:]
    key = _load_key()
    try:
        plaintext = AESGCM(key).decrypt(
            nonce,
            ciphertext,
            str(chat_id).encode("utf-8"),
        )
    except Exception as exc:
        # InvalidTag → tampered ciphertext, wrong key, or chat_id (AAD) mismatch.
        # All are unrecoverable; the caller should force re-authentication.
        logger.error("AES-GCM decrypt failed for chat_id=%s: %s", chat_id, exc)
        raise TokenEncryptionError(f"Token decryption failed: {exc}") from exc

    return plaintext.decode("utf-8")
